baseurl      = "https://leftl.github.io"
title        = "Tyler Waters"
languageCode = "en-us"
theme        = "hello-friend-ng"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = ".public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Tyler Waters"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "01-02-2006"
  dateformNumTime = "01-02-2006 3:04 PM"

  # Subtitle for home
  homeSubtitle = "Junior Computer Science student @ the University of Washington"

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a> &amp; <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Hello Friend NG</a>"
  footerRight = "View this site on <a href=\"https://github.com/leftl/leftl.github.io\">GitHub</a>"

  # Social icons
  #[[params.social]]
  #  name = "twitter"
  #  url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:tylerwaters@outlook.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/leftl"

  #[[params.social]]
  #  name = "linkedin"
  #  url  = "https://www.linkedin.com/"

  #[[params.social]]
  #  name = "stackoverflow"
  #  url  = "https://www.stackoverflow.com/"

[languages]
  [languages.en]
    title = "Tyler Waters"
    subtitle = "Student & Tinkerer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "tyler@localhost: ~$ "
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"